### ISSUE TITLE
How load css files to window ?

### ISSUE THREAD

**Issue by SudoDios** [jwharm/java-gi#114]
Can show example ?
StyleContext is depricated !

**Comment by jwharm** [comment]
Deprecation does not mean you cannot use it. It indicates what will change in the next major Gtk version.

But in this case you can use `StyleContext.addProviderForDisplay()` which isn't deprecated. It will load a css file that defines the style of the entire application, instead of setting a style for individual widgets (which has been deprecated).

[Example](https://github.com/jwharm/java-gi-examples/blob/main/Calculator/src/main/java/io/github/jwharm/javagi/examples/calculator/Calculator.java#L53-L64)

**Comment by SudoDios** [comment]
I know 😊.
But I meant that maybe there is an alternative method.
Thanks
