### ISSUE TITLE
"Type" is null when generating bindings for spice-client-glib

### ISSUE THREAD

**Issue by Tennessene** [jwharm/java-gi#91]
I am trying to generate Java bindings for a library called spice-client-glib. It is part of the [spice-gtk](https://gitlab.freedesktop.org/spice/spice-gtk) project. When I run the command to build the sources, I get an error that is displayed below.
```
> Task :buildSrc:compileJava
Note: /home/asorensen/java-gi/buildSrc/src/main/java/io/github/jwharm/javagi/gir/Field.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use preview features of Java SE 21.
Note: Recompile with -Xlint:preview for details.
 
> Task :spiceclientglib:generateSources FAILED
 
FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':spiceclientglib:generateSources'.
> Cannot invoke "io.github.jwharm.javagi.gir.RegisteredType.name()" because "type" is null
 
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
 
BUILD FAILED in 20s
46 actionable tasks: 44 executed, 2 from cache
```
As shown in the error, the main issue is that it can't get the name of the `RegisteredType` because `type` is null. I only have a basic understanding of how Java GI works, so I don’t really know what is going on here. I wish I knew more about what it was talking about.

This is most likely a bug, so hopefully it won’t be too difficult to fix this. Consider it an opportunity to improve Java GI though.

I will attach the GIR file I have of the library. It will be in a zip file. I created the GIR file by compiling the spice-gtk project on my system that runs Ubuntu 22.04 (it’s a GIR file for Linux).

[SpiceClientGLib-2.0.zip](https://github.com/jwharm/java-gi/files/14859332/SpiceClientGLib-2.0.zip)

**Comment by jwharm** [comment]
There are three separate issues processing the spice-client-glib gir file. The first one is a bug in Java-GI, the two others require "patching" the gir data.

1. `VReader` is declared in the gir as a  `<glib:boxed>` type. This element doesn't occur a lot in other gir files, and as it turns out, it's not handled in several places. Luckily, this was an easy fix.

2. In the Audio class, the virtual method `get_playback_volume_info_finish` has a `volume` parameter of type `guint16**`. I guess that's a pointer to an array of 16-bit int values, but I'm not sure. How are we supposed to know the size of the array? I don't know how to marshal this to Java values.

3. Finally, in the Channel class, the method `spice_channel_open_fd` causes an issue, because Channel also contains a member `(*open_fd)`, the `open-fd` signal handler. Java-GI generates an `openFd(int)` method for both, but that obviously doesn't work. The best solution in my opinion is to rename `spice_channel_open_fd` (on the Java side).

I fixed the Boxed type handling in #0b8fa38 and added `spice` branch with a "patch" class to Java-GI for the Spice gir file to change the `guint16**` type to an opaque `gpointer` and rename `Channel::openFd` to `Channel::openSocket`.

**Comment by Tennessene** [comment]
Thanks a lot. It works now. So that's why introspection data needs to be patched. Will this branch be merged with main then when ready?

So you had to look through the gir file and have the prior knowledge to know exactly what to fix/patch?

**Comment by jwharm** [comment]
I can merge the branch, but won’t be able to do regression tests in future releases.

The bug with boxed types showed up with a debugger. The two other issues were compile errors on the generated code, so I could quickly check the relevant parts if the gir file.

**Comment by Tennessene** [comment]
I will close this now
